version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - SECRET_KEY_BASE="TooLongTextForExampleAAAAAAaaaazJky2YrhKU8WVfxyA4ePuWpdR0+WI2yGiNmHxThiehy3ztYXwRtZdaaaaaaaaaaaaaaaaaa"
    stdin_open: true
    tty: true
    command: sh -c "mix phx.server --no-halt"
