version: "3"
services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    stdin_open: true
    tty: true
    working_dir:
      /kokuraex
    command:
      sh -c "ls -a && mix serum.server"
