version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    stdin_open: true
    tty: true
    command: sh -c "mix phx.server --no-halt"
