version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:edge

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

jobs:
  build:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            set -x
            docker compose build
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            docker compose run app bash -c "mix deps.get"
            docker compose run app bash -c "mix compile"
      - run:
          name: Mix format
          command: |
            set -x
            docker compose run app bash -c "mix format --check-formatted"
      - run:
          name: Mix test
          command: |
            set -x
            docker compose run app bash -c "MIX_ENV=test mix test"
      - run:
          name: Compile assets
          command: |
            set -x
            docker compose run app bash -c "MIX_ENV=prod mix assets.deploy"
      - run:
          name: Mix release
          command: |
            set -x
            docker compose run app bash -c "MIX_ENV=prod mix release"
      - run:
          name: Run Docker image
          command: |
            set -x
            docker compose up -d
            sleep 1
            docker ps -f status=running
            docker compose logs
      - run:
          name: Finish build
          command: |
            set -x
            echo "Finish build"
