version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:edge

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: main

jobs:
  test:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build a development Docker image
          command: |
            set -x
            docker compose build
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            docker compose run app bash -c "mix deps.get"
            docker compose run app bash -c "mix compile"
      - run:
          name: Mix format
          command: |
            set -x
            docker compose run app bash -c "mix format --check-formatted"
      - run:
          name: Mix test
          command: |
            set -x
            docker compose run app bash -c "MIX_ENV=test mix test"
      - run:
          name: Mix dialyzer
          command: |
            set -x
            docker compose run app bash -c "mix dialyzer"
      - run:
          name: Finish test
          command: |
            set -x
            echo "Finish test"

  build:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build a production Docker image
          command: |
            set -x
            docker build -t kokuraex -f app/Dockerfile app/
      - run:
          name: Run Docker image for activation check
          command: |
            set -x
            docker run -d -p 4000:4000  \
            -e SECRET_KEY_BASE="dummy_key" \
            --name kokuraex kokuraex
            sleep 5
            docker ps -f status=running
            docker logs kokuraex
      - run:
          name: Finish build
          command: |
            set -x
            docker stop kokuraex
            echo "Finish build"

  deploy:
    deploy:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Run Render deploy hook
          working_directory: app
          command: |
            curl -X POST $RENDER_DEPLOY_HOOK_URL
      - run:
          name: Finish deploy
          command: |
            set -x
            echo "Finish deploy"
